### Installation
use the Jupyter plugin, Jupyter notebook, Google Colab or ipython

`pip install ipython` or `python3 -m pip install ipython`

## Warmup 1: Vector operations

In [3]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.float32)

In [ ]:
a + 10   # numpy eliminates loops from our code - good!

array([11., 12., 13.], dtype=float32)

In [ ]:
a * 100  # scalar multiplication

array([100., 200., 300.], dtype=float32)

In [7]:
b = np.array([4, 5, 6], dtype=np.float32)
a * b  # vector multiplication

array([ 4., 10., 18.], dtype=float32)

In [9]:
np.dot(a, b)  # dot product: sum(a*b)

np.float32(32.0)

In [12]:
np.log(a)

array([0.       , 0.6931472, 1.0986123], dtype=float32)