In [2]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3]]) # one-row-matrix
a.shape  # rows, cols

(1, 3)

In [8]:
b = np.array([[4], [5], [6]])  # one-column-matrix
b.shape

(3, 1)

In [9]:
a * b

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [10]:
a.shape, b.shape

((1, 3), (3, 1))

In [11]:
np.dot(a, b)

array([[32]])

In [12]:
np.dot(b, a)

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])