# Gradient Descent

* we now have an extra dimension: x2
* x1 and x2 are the *independent variables*
* y is the *dependent variable*

with two x dimensions, we get a plane:

$\hat y = a_1x_1 + a_2x_2 + a_0*1$

the model has 3 parameters (a0, a1, a2)

$\hat y = aX$

a is a vector of parameters, X is a matrix with our input training data. aX is a dot product of a vector and a matrix.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("linear07.csv")
df["bias"] = 1
#df.head(3)

#### Problem: how to find the optimal parameters if we cannot use nested loops and try all combinations?

In [3]:
# select training data
X = df[["x1", "x2", "bias"]]  # if you leave away the bias, the regression goes through the origin (0,0)
ytrue = df["y"]

X.shape, ytrue.shape  # X is a 2D matrix, ytrue is a vector

((1000, 3), (1000,))

### Linear Model

In [4]:
def linear_model(X, a):
    return np.dot(X, a)

In [5]:
a = np.array([1, 2, 3])      # arbitrary parameters for testing
yhat = linear_model(X, a)    # output is 1000 values for y
yhat.shape

(1000,)

### Loss Function

In [6]:
def mse(ytrue, yhat):
    return np.mean((ytrue - yhat) ** 2)

In [7]:
mse = lambda ytrue, yhat: np.mean((ytrue - yhat) ** 2)  # same code but messy in bigger program

In [8]:
# test code with example numbers by Paul
a = np.array([1.0, 1.2, 1.4, 1.6])
b = np.array([0.2, 0.4, 0.6, 0.8])

assert round(mse(a, b), 2) == 0.64  # if there is no error it is correct

In [9]:
mse(ytrue, ytrue)  # 0.0 is the smallest possible MSE value

0.0

### Gradient

$a_{new} = a_{old} - \eta \nabla loss(a)$

In [18]:
def partial_derivative(X, ytrue, a, index, mse_old, epsilon=0.0001):
    """determine by how much we have to modify the indexed parameter"""
    a_change = a.copy()
    a_change[index] += epsilon
    ypred_a = linear_model(X=X, a=a_change)
    mse_a = mse(ytrue, ypred_a)
    return (mse_a - mse_old) / epsilon


def calc_gradient(X, ytrue, a):
    ypred = linear_model(X=X, a=a)   # prediction for y with the parameters we have now
    mse_old = mse(ytrue, ypred)

    result = []
    for index in range(3):
        result.append(partial_derivative(X, ytrue, a, index, mse_old))
    return result  # all partial derivatives for each parameter -> list of 3 numbers used to calculate Delta_a

In [19]:
np.random.seed(42)            # set the seed value of the random number generator
a = np.random.random(size=3)  # random parameter vector
a

array([0.37454012, 0.95071431, 0.73199394])

In [34]:
gradient = np.array(calc_gradient(X=X, ytrue=ytrue, a=a))
gradient

array([ -591.47557525, -2588.37815704,  -114.44204074])

In [35]:
learning_rate = 0.0001
a_new = a - gradient * learning_rate
a_new

array([0.57427937, 1.82365212, 0.77058999])

In [36]:
# before
ypred = linear_model(X=X, a=a)
mse_old = mse(ytrue, ypred)
mse_old

3308.830130162704

In [37]:
# new
ypred = linear_model(X=X, a=a_new)
mse_new = mse(ytrue, ypred)
mse_new

2640.244283671306

In [33]:
a = a_new